### ISSUE TITLE
Multi App Staking (MAS) Usability Testing

### ISSUE THREAD

**Issue by liz-shinn** [threshold-network/token-dashboard#145]
# Overview
We will test the Staking Flow alongside with the Multiple Application Authorization Flow for existing stakers and new stakers. 
The Staking flow has never been tested out before so it is an opportunity to bring improvements to this flow as well since the Stakers are the backbone of our network.

## Additional Context:
* PRE application was believed it needs authorization, it turned out it’s already authorized for existing stakers. 
* Existing Stakers who have set an Authorizer Address different from the Owner Address are required to take a separate route to authorize their stakes.

## 🎯 Goals
* Map out thoughts and feelings about the Staking Process and the Staking Requirements
* Identify the possible issues and misalignments with the users’ mental models
* Uncover the friction points in the Staking and MAS User Journey
* Identify team’s blind spots on Staking and MAS
* Probe our assumptions with real data

## 🤼 Team 
🐱 **User Researcher**: Sasha Tanase
👓 **Observer**: Liz Shinn, hopefully some other team members
🦄 **Product Designers**: Sasha Tanase, Liz Shinn
👾 **Frontend Engineers**: Rafal Cza, George Weiler

Full documentation in Coda.

## Tasks
- [x] Source 8-12 participants in the two cohorts
- [x] Design and write the user study script and goals
- [x] Schedule 9 participants
- [x] Interview 9 participants
- [x] finding solutions to better the designs and improve usability
- [x] Analyze raw data from notes from 9 participants
- [x] Create a report of recommended changes and their priority
- [x] Review the report with the team
- [x] Make changes to the Figma designs based on the findings (tracked in a separate issue (https://github.com/threshold-network/token-dashboard/issues/146)

**Comment by sashatanase** [comment]
Usability Report [here ](https://docs.google.com/presentation/d/1PG0OR-g7etk87_1KbRMjrLN4u2tCib-7kySF0lcV3Tk/edit?usp=sharing)

**Comment by sashatanase** [comment]
Prioritization Workshop [here](https://miro.com/app/board/uXjVPdA0AQM=/?share_link_id=650243397144)

![image](https://user-images.githubusercontent.com/40768736/186459454-c201a778-9f87-4fd7-a8ee-7508db00c3f3.png)

Prioritization workshop finished.
Some decisions made to improve and make the implementation easier and faster:

- breadcrumbs left aligned in the centre container.
- for the cases with more than one stake, all of the stakes will be left aligned in one column.
