### ISSUE TITLE
Threshold Coverage Pool Designs

### ISSUE THREAD

**Issue by liz-shinn** [threshold-network/token-dashboard#180]
Designs for Threshold Coverage Pool, based on the Keep dashboard coverage pool.

# Tasks
- [x] Pull in wireframes from Keep Cov Pool into Figma
- [x] Refer to user flows for Keep Cov Pool - https://miro.com/app/board/o9J_lI7iJ6Q=/
- [x] Deposit Pool Flow
- [x] How it Works page
- [x] Cov Pool Illustration diagram
- [x] covT icon
- [x] Exit Pool Flow
- [x] Cooldown Complete
- [x] Claim Window Expired
- [x] Wants to increase the amount of their withdrawal
- [x] Wants to increase the amount of their withdrawal but has claimable tokens
- [x] Covered Loss

Prototyping
- [x] Clickable prototype v1
- [x] Revisions
- [ ] Review with engineering team

# Useful Files
Miro User Flows: https://miro.com/app/board/o9J_lI7iJ6Q=/
Figma File: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=5809%3A140442

**Comment by liz-shinn** [comment]
![Image](https://user-images.githubusercontent.com/57226633/189405067-9ed5a563-0669-433a-8704-6db2c7ae7edb.png)

**Comment by liz-shinn** [comment]
![Image](https://user-images.githubusercontent.com/57226633/189460309-42ee675c-a9d3-43bf-a8ad-9ea5fd374dc8.png)
![Image](https://user-images.githubusercontent.com/57226633/189460310-d82c9902-9f7b-42c2-bd8f-e3618e432303.png)
![Image](https://user-images.githubusercontent.com/57226633/189460311-b05b57a8-1852-41f7-a54c-5f1cfafdd81d.png)

**Comment by liz-shinn** [comment]
Clickable protoype: https://www.figma.com/proto/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?page-id=6417%3A163240&node-id=6417%3A165963&viewport=-216%2C-103%2C0.05&scaling=min-zoom&starting-point-node-id=6417%3A165963&show-proto-sidebar=1
