### ISSUE TITLE
EPIC: Launch on Base Chain

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#534]
```[tasklist]
### Base release
- [ ] Threshold Council redeploys the safe on Base 
- [ ] Deploy L2 canonical token and gateway to Base
- [ ] Wormhole team integrates it in the Portal UI 
- [ ] Test Wormhole Base implementation in Portal UI

```
