### ISSUE TITLE
EPIC: COVERAGE POOL

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#538]
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/issues/530
- [ ] Write docs entry for coverage pool
- [ ] Announce coverage pool
```
