### ISSUE TITLE
Modify TVL label in dashboard with more descriptive terms

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#589]
- [x] Change **TVL** to **TOTAL SUPPLY** to be consistent with the Dune Dashboard labels
- [x] Change the **TOTAL VALUE LOCKED** to  **TOTAL TVL (BTC + STAKING)** (which should be around $124M)

![image](https://github.com/threshold-network/token-dashboard/assets/14485/a00eb7e3-a43f-4df0-926d-5547fa298270)

```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/629
```

**Comment by michalsmiarowski** [comment]
@erdogan I need more details about this:

> Change the TOTAL VALUE LOCKED to TOTAL TVL (BTC + STAKING) (which should be around $124M)

What do we actually want to include in our calculations for `TOTAL TVL (BTC + STAKING)`? Additionally, could you please specify the source of the `$124M` value? Is this figure available on the Dune dashboard?"

Right now we include tokens from staking, tbtc, coverage pools and ecdsa. You can see it here: https://github.com/threshold-network/token-dashboard/blob/main/src/hooks/useFetchTvl.ts#L178-L185
