### ISSUE TITLE
Initial technical assessment: what's possible and feasible

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#619]
```[tasklist]
### Tasks
- [x] Prepare a mock dapp subpage and run it as Ledger Live iframe application (see https://developers.ledger.com/docs/live-app/start-here and https://github.com/LedgerHQ/eth-dapp-browser)
- [x] Detect user accounts and use them to perform ETH transactions
- [x] Check if iframe dapp can redirect back to Ledger Live (for example, to Accounts section)
- [x] Check if there is possible to send BTC transaction from iframe dapp using Ledger Live BTC accounts
- [x] Check if electrum works and see if the whole tbtc flow will work without leaving the Ledger App [Michal]
- [x] Explore `useSignMessage` hook (https://wallet.api.live.ledger.com/react/hooks/useSignMessage) [Rafal]
```

Edited by @michalsmiarowski:

Explore `useSignMessage` hook:
- Can we sign a message with a Bitcoin account?
- How can we derive the account?
- Can we use any derivation path?
- Are there any restrictions?
- Can we pull a public key for the given Bitcoin account?
- Can it produce [BIP-137](https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki) and [BIP-322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) compliant signatures?
