### ISSUE TITLE
Switch dApp to SDK `v1.4.1`

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/token-dashboard#647]
Currently, the Threshold Dashboard uses an old SDK version:
- For development (pinned in the `package.json`): `@keep-network/tbtc-v2.ts@v1.3.0-dev.9`
- For Goerli: `@keep-network/tbtc-v2.ts@v1.3.0-goerli.1`
- For mainnet: `@keep-network/tbtc-v2.ts@v1.3.0`

The recent `typescript/v1.4.0` release (https://github.com/keep-network/tbtc-v2/releases/tag/typescript/v1.4.0) of the `@keep-network/tbtc-v2.ts` library introduces some major changes like `bcoin` dependency removal and support for Node 18 LTS. We need to adjust the dApp to work with the following versions:

- For development (pinned in the `package.json`): `@keep-network/tbtc-v2.ts@v2.0.0-dev.0`
- For Goerli: `@keep-network/tbtc-v2.ts@v1.4.1-goerli.0`
- For mainnet: `@keep-network/tbtc-v2.ts@v1.4.1`

This translates to the following task list:

```[tasklist]
### Tasks
- [x] Change `package.json` to use `@keep-network/tbtc-v2.ts@v2.0.0-dev.0`
- [x] Make sure `yarn.lock` reflects that change
- [x] Make all necessary code adjustments to make the dApp build successful
- [x] Make sure dApp works with Node 18 LTS (think about adding the `engines.node: >=16` rule in the `package.json`
- [x] Make sure dApp builds with `@keep-network/tbtc-v2.ts@v1.4.1-goerli.0`
- [x] Make sure dApp build with `@keep-network/tbtc-v2.ts@v1.4.1`
- [ ] Make basic regression tests on `https://dashboard.test.threshold.network`
- [ ] Make basic regression tests on mainnet preview
- [ ] Once this task is done. Release the new dApp on mainnet
```
