### ISSUE TITLE
Switch dApp to SDK `v2.0.0`

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/token-dashboard#648]
Depends on: https://github.com/threshold-network/token-dashboard/issues/647 and SDK `typescript/v2.0.0` release.

We need to make the same adjustments as in https://github.com/threshold-network/token-dashboard/issues/647 but for the `typescript/v2.0.0` release. This translates to the following task list:

```[tasklist]
### Tasks
- [x] Change `package.json` to use `@keep-network/tbtc-v2.ts@v2.0.0` (one version for all networks as chain configs are embedded now). We should probably use the caret `^` sign to allow upgrades to future compatible versions
- [x] Make sure `yarn.lock` reflects that change
- [x] Make all necessary code adjustments to make the dApp build successful (initialize the SDK properly for the given environment)
- [x] Make sure the dApp does no longer depend on `@keep-network/tbtc-v2` and `@keep-network/ecdsa` packages directly. All contract interactions should be handled through SDK
- [x] Make necessary changes in CI jobs
- [x] Make basic regression tests on `https://dashboard.test.threshold.network`
- [x] Make basic regression tests on mainnet preview
- [x] Once this task is done. Release the new dApp on mainnet
```

```[tasklist]
### PRs
- [ ] https://github.com/threshold-network/token-dashboard/pull/654
- [ ] https://github.com/threshold-network/token-dashboard/pull/662
- [ ] https://github.com/threshold-network/token-dashboard/pull/663
- [ ] https://github.com/threshold-network/token-dashboard/pull/664
```
